config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "page#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i[ show edit update destroy ]

  # GET /galleries or /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1 or /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
    respond_to do |format|
      format.js
    end
  end

  # GET /galleries/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /galleries or /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: "Gallery was successfully created." }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1 or /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: "Gallery was successfully updated." }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1 or /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: "Gallery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gallery_params
      params.require(:gallery).permit(:title, :description, images: [])
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @galleries = Gallery.with_attached_images
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery, html: { multipart: true, class: "contact-form" } do |form| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field-wrapper">
    <%= form.text_field :title, placeholder: :title, class: "input-sm form-full", require: true %>
  </div>

  <div class="form-field-wrapper">
    <%= form.text_area :description, placeholder: :description, class: "form-full" %>
  </div>

  <div class="form-field-wrapper">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "input-sm form-full" %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-md btn-black form-full" %>
  </div>
<% end %>

app/views/galleries/_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
<div class="modal-body">
  <h4 class="modal-title" id="myModalLabel">New Gallery</h4>
  <%= render 'form' %>
</div>

<div class="modal inmodal fade" id="search" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Documents</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12">
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<section class="inner-intro dark-bg bg-image overlay-dark parallax parallax-background1" data-background-img="<%= asset_path 'img/bkg-gallery.png' %>">
  <div class="container">
    <div class="row title">
      <h2 class="h2">Gallery</h2>
      <div class="page-breadcrumb">
        <%= link_to "Home", root_path %>/<span>Gallery</span>
      </div>
      <br>
      <%= link_to 'New Gallery', new_gallery_path, remote: true %>
    </div>
  </div>
</section>

<section class="ptb ptb-sm-80">
  <div class="container-fluid">
    <p id="notice"><%= notice %></p>
    <!-- Filter list 
    <div class="row">
      <ul class="col container-filter categories-filter">
        <li><a class="categories active" data-filter="*">All</a></li>
        <li><a class="categories" data-filter=".branding">Branding</a></li>
      </ul>
    </div>
    -->

      <div class="container-masonry nf-col-4">
        <% @galleries.each do |g| %>
          <% g.images.each do |a| %>
            <div class="nf-item branding">
              <div class="item-box">
                <%= link_to g do %>
                  <%= image_tag a, class: "item-container", atl: g.title %>
                  <div class="item-mask">
                    <div class="item-caption">
                      <h5 class="white"><%= g.description %></h5>
                      <p class="white"><%= g.title %></p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</section>

<!-- Form Modal -->
<div class="modal inmodal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/galleries/new.html.erb
<%= render 'form', gallery: @gallery %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/new.js.erb
$("#modal .modal-content").html('<%= j render "modal" %>');
$("#modal").modal();

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gallery.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gallery.description %>
</p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galicia2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Favicone Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">
    <link rel="icon" type="image/png" href="img/favicon.png">
    <link rel="apple-touch-icon" href="img/favicon.png">

    <!-- CSS -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/font-awesome.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/ionicons.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/plugin/animate.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/jquery-ui.css" rel="stylesheet" type="text/css" />
  </head>

  <body>
    <!-- Preloader -->
    <section id="preloader">
      <div class="loader" id="loader">
        <div class="loader-img"></div>
      </div>
    </section>

    <!-- Sidebar Menu -->
    <%= render 'shared/sidebar' %>

    <!-- Site Wraper -->
    <div class="wrapper">
      <%= render 'shared/header' %>

      <%= yield %>

      <div class="clearfix"></div>
    </div>

    <!-- JS -->
    <%= render 'shared/js' %>
  </body>
</html>

app/views/page/home.html.erb
<section id="intro">
  <div class="flexslider fullscreen-carousel hero-slider-1 ">
    <ul class="slides">
      <% if @galleries.any? %>
        <% @galleries.each do |gallery| %>
          <li data-slide="light-slide">
            <div class="slide-bg-image overlay-light parallax parallax-section1" data-background-img="<%= rails_blob_url(gallery.images.first) %>">
              <div class="js-Slide-fullscreen-height container">
                <div class="intro-content">
                  <div class="intro-content-inner">
                    <h2 class="h2"><%= gallery.title %></h2>
                    <p class="lead"><%= gallery.description %></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      <% else %>
        <li data-slide="light-slide">
          <div class="slide-bg-image overlay-light parallax parallax-section1" data-background-img="<%=  asset_path 'img/bkg-gallery.png' %>">
            <div class="js-Slide-fullscreen-height container">
              <div class="intro-content">
                <div class="intro-content-inner">
                  <h2 class="h2">Welcome to Galicia II</h2>
                  <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus bibendum.</p>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</section>

app/views/shared/_header.html.erb
<header id="header" class="header header-transparent header--sticky">
  <!-- Nav Bar -->
  <nav id="navigation" class="header-nav">
    <div class="container">
      <div class="row d-flex flex-md-row align-items-center">
        <div class="logo mr-auto">
          <a href="index.html">
          <%= link_to root_path do %>
            <img class="logo-dark" src="<%= asset_path 'img/logo-black.png' %>" alt="GaliciaII" />
            <img class="logo-light" src="<%= asset_path 'img/logo-white.png' %>" alt="GaliciaII" />
          <% end %>
        </div>

        <div class="nav-icons">
          <div class="nav-icon-item d-lg-none">
            <span class="nav-icon-trigger menu-mobile-btn align-middle"><i class="ion"></i></span>
          </div>
          <div class="nav-icon-item">
            <span class="nav-icon-trigger sidebar-menu_btn align-middle"><i class="ion ion-navicon"></i></span>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <!-- End Nav Bar -->
</header>

app/views/shared/_js.html.erb
<script src="/assets/js/jquery-1.11.2.min.js" type="text/javascript"></script>
<script src="/assets/js/plugin/jquery.easing.js" type="text/javascript"></script>
<script src="/assets/js/jquery-ui.min.js" type="text/javascript"></script>
<script src="/assets/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/js/plugin/jquery.flexslider.js" type="text/javascript"></script>
<script src="/assets/js/plugin/jquery.fitvids.js" type="text/javascript"></script>
<script src="/assets/js/plugin/jquery.viewportchecker.js" type="text/javascript"></script>
<script src="/assets/js/plugin/jquery.stellar.min.js" type="text/javascript"></script>
<script src="/assets/js/plugin/wow.min.js" type="text/javascript"></script>
<script src="/assets/js/plugin/jquery.colorbox-min.js" type="text/javascript"></script>
<script src="/assets/js/plugin/owl.carousel.min.js" type="text/javascript"></script>
<script src="/assets/js/plugin/isotope.pkgd.min.js" type="text/javascript"></script>
<script src="/assets/js/plugin/masonry.pkgd.min.js" type="text/javascript"></script>
<script src="/assets/js/plugin/imagesloaded.pkgd.min.js" type="text/javascript"></script>
<script src="/assets/js/plugin/jquery.fs.tipper.min.js" type="text/javascript"></script>
<script src="/assets/js/plugin/mediaelement-and-player.min.js"></script>
<script src="/assets/js/theme.js" type="text/javascript"></script>

app/views/shared/_sidebar.html.erb
<div class="sidebar-menu">
  <div class="sidembar-menu-wrap">
    <a href="javascript:void(0)" class="sidebar-close-icon icon--close">
      <i class="ion ion-android-close"></i>
    </a>

    <div class="sidebar-content">
      <h5 class="white">Sign In</h5>
      <form role="search" id="searchform" action="/search" method="get" class="sign-in">
        <input class="input-sm form-full" type="email" aria-required="true" id="email" name="email" placeholder="Email" value="" />
        <input class="input-sm form-full" type="password" aria-required="true" id="password" name="password" placeholder="Password" value="" />
        <input type="submit" class="btn btn-md btn-color-b form-full" value="Sign In" />
      </form>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Gallery", galleries_path %></li>
      </ul>
    </div>
  </div>
</div>